server:
  port: 7902
spring:
  application:
    name: consumer-hello
#    
#  thymeleaf:
#    prefix: /static
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .html
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
logging:
  level:
    root: INFO

