
server:
  port: 7900
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
logging:
  level:
    root: INFO
    
    
spring:
   application:
    name: provider-user
    
   datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cms
    username: root
    password: root
    hikari:
      connection-timeout: 60000 
mybatis:
  mapper-locations: classpath*:mapper/query/*.xml
  type-aliases-package: com.dao.*

